# -*- coding: utf-8 -*-
"""Response 1 JULY 7th, 2020 

QUESTION 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/annetteclopezdavila/85cfc72d2f6c481b523f6b4460d6ed0a/exercise_1_house_prices_question.ipynb
"""

#MY CODE 
#import
import tensorflow as tf
import numpy as np
from tensorflow import keras

#create one layer neural network
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
#optimizer, loss
model.compile(optimizer='sgd', loss='mean_squared_error')
#data
x = np.array([4.0,3.0,5.0,4.0,2.0,3.0], dtype=float)
y = np.array([3.99,0.97,5.77,2.89,2.50,2.29], dtype=float)

#fit model
model.fit(x, y, epochs=1000)

#if X=7 what is Y?
print('Model Predictions(by bedroom):')
print( model.predict([1.0]))
print( model.predict([2.0]))
print(model.predict([3.0]))
print(model.predict([4.0]))
print(model.predict([5.0]))

print('Actual price- predicted value by bedroom:')
print('984 fitchets(2 beds)')
print(2.50- 1.3919599)
print('160 holly point(3 beds)')
print(0.97-2.5239644)
print('4403 new point comfort hwy (3 beds)')
print(2.29-2.5239644)
print('6138 river road (4 beds)')
print(2.89-3.649573)
print('228 church street(4 beds)')
print(3.99-3.649573)
print('760 new point comfort (5 beds)')
print(5.77-4.7566595)

